### ISSUE TITLE
Is there a process to update and release new images for new PHP-FPM releases?

### ISSUE THREAD

**Issue by rmetzler** [exozet/docker-php-fpm#120]
There is Version 7.3.13 https://www.php.net/ChangeLog-7.php#7.3.13

latest version I see on Docker Hub is 7.3.10

https://hub.docker.com/r/exozet/php-fpm/tags?page=1&name=7.3.10

**Comment by rmetzler** [comment]
Should I use

```
FROM exozet/php-fpm:7.3-sudo AS php
```

in my Dockerfile to get the latest release or should I be more specific (e.g use `7.3.10-sudo` as label)?

I assume this is using semver?

**Comment by DracoBlue** [comment]
1. just create a pr to the specific branch with the new version added. -> I created one for 7.3.13 https://github.com/exozet/docker-php-fpm/pull/121
2. use explicit version like 7.3.10-sudo

**Comment by DracoBlue** [comment]
7.3.13 is now available
