### ISSUE TITLE
make opcache configurable

### ISSUE THREAD

**Issue by DracoBlue** [exozet/docker-php-fpm#140]
It would be good to have those configureable

```
RUN echo "opcache.memory_consumption=\${PHP_OPCACHE_MEMORY_CONSUMPTION}" >> /usr/local/etc/php/php.ini
RUN echo "opcache.max_accelerated_files=\${PHP_OPCACHE_MAX_ACCELERATED_FILES}" >> /usr/local/etc/php/php.ini
RUN echo "opcache.validate_timestamps=\${PHP_OPCACHE_VALIDATE_TIMESTAMPS}" >> /usr/local/etc/php/php.ini
```

defaults are at https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.validate-timestamps

Done + Branch in:

- [x] 7.0
- [x] 7.1
- [x] 7.2
- [x] 7.3
- [x] 7.4

**Comment by OskarStark** [comment]
If you are maintaining some legacy code, would you mind add these variables to `7.0`, too?

**Comment by niepi** [comment]
added php 7.0 #154

**Comment by OskarStark** [comment]
Thank you @niepi 🤩
