### ISSUE TITLE
include additional software in image

### ISSUE THREAD

**Issue by niepi** [exozet/docker-php-fpm#15]
installing missing packages takes time in our gitlab builds , it would be nice if we could integrate some additional software into this image.

we would need:

- mysql-client (importing db-dumps this way is much faster the the symfony doctrine import command)
- rsync (syncing with our build repository
- sshpass (for special deployments)

**Comment by DracoBlue** [comment]
except sshpass feel free to create a PR for this

**Comment by DracoBlue** [comment]
PS: sshpass is really a bad bad practice

**Comment by DracoBlue** [comment]
PPS: i use a dedicated rsync step in gitlab ci with a rsync image. Is this an option for you, too?

**Comment by niepi** [comment]
Rsync image task - sure this would work, but will add much more time to the hole build process for the extra task
sshpass - we have deployments where we have no key authentication and there is this the only option


I will create a PR

**Comment by OskarStark** [comment]
Why not creating a custom dev image for a project which is based on `docker-php-fpm` image?

Shouldn't be that hart to add a gitlab pipeline or travis build

**Comment by DracoBlue** [comment]
Merged #17
