### ISSUE TITLE
Question: How to handle composer v2?

### ISSUE THREAD

**Issue by hoffigk** [exozet/docker-php-fpm#170]
Composer v2 is out and it would be nice to update all images to this version, but it can break existing applications.

So my question is: How to handle the composer v2 integration?

1. Install both versions of composer and control the needed version via symlink?
2. Create a new version schema for the images like `exozet/php-fpm:7.3-v1.0-sudo` to indicate the php version and the version of containing features?

The second suggestion would also be useful to make visible that not only the PHP version has changed, but also the included features, like composer or php extension and so on.

More version examples:

- `exozet/php-fpm:7.4-v1.0-sudo` -> contains patches for php and feature set
- `exozet/php-fpm:7.4-v1.0.0-sudo` -> contains patches for php and explicit version for feature set
- `exozet/php-fpm:7.4.11-v1.0-sudo` -> contains explicit php version and patches for feature set
- `exozet/php-fpm:7.4.11-v1.0.0-sudo` -> explicit version for php and feature set
- `exozet/php-fpm:7.4.11-v2.0.0-sudo` -> explicit version for php and feature set

**Comment by niepi** [comment]
I would prefer the 2. approach. 

Keep the tag schema for the old version, but added also the new tags, so we don't introduce breaking changes. 

For composer I would only tag the mayor version.

**Comment by OskarStark** [comment]
I would prefer to install composer 1 and 2 and make it configurable via ENV

**Comment by niepi** [comment]
I'm working to implement what @OskarStark suggested, but I don't understand how/where composer is downloaded.

can someone explain what happens here https://github.com/exozet/docker-php-fpm/blob/release/7.4/7.4/Dockerfile#L66

**Comment by OskarStark** [comment]
Important is the line:
https://github.com/exozet/docker-php-fpm/blob/22c39f1478915dfa2145475120be060657c1adb6/7.4/Dockerfile#L67

It pulls the build composer image and extracts the compiled binary.

IMHO this should do the trick:
```diff
- COPY --from=composer:1.8.6 /usr/bin/composer /usr/local/bin/composer
+ COPY --from=composer:${COMPOSER_VERSION} /usr/bin/composer /usr/local/bin/composer
```

+ getting the configured value into the Dockerfile

**Comment by niepi** [comment]
thx, my approach would be:

- install both version to ```/usr/local/bin/composer1|2```
- make ```/usr/local/bin/composer``` a script the selects the version based on COMPOSER_VERSION

**Comment by niepi** [comment]
#173 i have created a pull request for 7.4 for this, since composer 2 support goes down to php5.3, i can port this later to the other versions

**Comment by niepi** [comment]
the mentioned approach was merged to all release branches, i think this closes this issue.

**Comment by OskarStark** [comment]
Thanks!
