### ISSUE TITLE
Php8?

### ISSUE THREAD

**Issue by DracoBlue** [exozet/docker-php-fpm#187]
- [ ] amqp extension fails to install https://github.com/php-amqp/php-amqp/issues/386#issuecomment-754184017
- [ ]  add -debian suffix for debian builds
- [ ]  use -alpine version as default, too

**Comment by DracoBlue** [comment]
@niepi / @OskarStark

**Comment by DracoBlue** [comment]
Do we want to do the alpine only switch?

**Comment by OskarStark** [comment]
> I look at this too over the holidays, but the build failed for me, because the rabbitmq deps where not working with php8 until now

@niepi we can keep this as a draft until every extension is working 👍

**Comment by niepi** [comment]
I can make a Draft PR, but against which branch?

**Comment by DracoBlue** [comment]
Against 7.4 and them we push it as 8.x

**Comment by DracoBlue** [comment]
At -alpine topic, I would like to have -debian suffix and -alpine suffix, but default to alpine for the unsuffixed ones (for CVE reasons!)

**Comment by DracoBlue** [comment]
https://github.com/exozet/docker-php-fpm/pull/188

**Comment by niepi** [comment]
@DracoBlue @OskarStark I think we can close this
