### ISSUE TITLE
major.minor images not updated

### ISSUE THREAD

**Issue by hoffigk** [exozet/docker-php-fpm#189]
The images exozet/php-fpm:7.3-* and  exozet/php-fpm:7.4-* are not updated after a new php version was added.

```
docker pull exozet/php-fpm:7.3-sudo 
7.3-sudo: Pulling from exozet/php-fpm
Digest: sha256:5b1358f24edcf98e86f3f1d65502709f9ae35acb82c4285bd00e3b22261bff99
Status: Image is up to date for exozet/php-fpm:7.3-sudo
docker.io/exozet/php-fpm:7.3-sudo
```

```
docker run --rm exozet/php-fpm:7.3-sudo php -v 
PHP 7.3.22 (cli) (built: Sep 10 2020 14:31:39) ( NTS )
```

Version is 7.3.22 but must be 7.3.25.

![Bildschirmfoto vom 2021-01-05 10-46-38](https://user-images.githubusercontent.com/1422975/103632402-87d22a00-4f44-11eb-8b85-b033e04638d5.png)

**Comment by OskarStark** [comment]
@DracoBlue can you please have a look, not so much time right now

**Comment by hoffigk** [comment]
ping @DracoBlue

**Comment by hoffigk** [comment]
I noticed that when pushing the image in the github action, the placeholders are showing instead of the values. Is it possible that there is a problem here?

![Bildschirmfoto vom 2021-03-02 10-05-52](https://user-images.githubusercontent.com/1422975/109625720-f0eaae00-7b3f-11eb-88c2-7c3ba4cde27b.png)

**Comment by hoffigk** [comment]
"major.minor" images fixed :)

**PHP 7.3**

docker run --rm exozet/php-fpm:7.3-sudo php -v 
PHP 7.3.27 (cli) (built: Feb  9 2021 20:10:23) ( NTS )

**PHP 7.4**

docker run --rm exozet/php-fpm:7.4 php -v 
PHP 7.4.15 (cli) (built: Feb  9 2021 19:48:41) ( NTS )

docker run --rm exozet/php-fpm:7.4-alpine php -v 
PHP 7.4.15 (cli) (built: Feb 18 2021 00:57:06) ( NTS )

**PHP 8.0**

docker run --rm exozet/php-fpm:8.0 php -v 
PHP 8.0.2 (cli) (built: Feb  9 2021 19:20:59) ( NTS )

docker run --rm exozet/php-fpm:8.0-alpine php -v 
PHP 8.0.2 (cli) (built: Feb 18 2021 00:32:13) ( NTS )
