### ISSUE TITLE
xdebug 3 for php 7.4 and 8

### ISSUE THREAD

**Issue by niepi** [exozet/docker-php-fpm#222]
I would like to propose switching to xdebug3 on the latest php versions (7.4 and 8)

Which options should be exposed as env vars?

this is my current dev config with docker
```
xdebug.mode=develop,debug
xdebug.client_host=host.docker.internal
xdebug.start_with_request=yes
```

**Comment by niepi** [comment]
I have seen now that php8 already has xdebug3, but not the right env vars exposed.

**Comment by DracoBlue** [comment]
Please expose „default“ values as default - if it makes sense.

**Comment by DracoBlue** [comment]
We could also advertise the usage of `XDEBUG_CONFIG` to set custom variables instead.

**Comment by niepi** [comment]
I like this approach, then we should maybe only expose XDEBUG_CONFIG and add a section to the README that explains the usage

**Comment by DracoBlue** [comment]
Can you check which values cannot be adjusted by this env?

**Comment by niepi** [comment]
I added XDEBUG_CONFIG ENV var
