### ISSUE TITLE
add nginx unit flavor

### ISSUE THREAD

**Issue by DracoBlue** [exozet/docker-php-fpm#275]
right now our images look like this: exozet/php-fpm:8.1.3-sudo. it would be good to also have exozet/php-nginx-unit:8.1.3-sudo with all our extensions but https://unit.nginx.org/ service the files. this could make it possible to delivery only this one image and not having to pair it with an extra nginx image.

Also https://habr.com/en/post/646397/ on some performance infos

**Comment by niepi** [comment]
I'm in favour of this. I also currently working on an 7.4 nginx unit image for one of my projectsand this is based on our fpm image

**Comment by DracoBlue** [comment]
Added https://habr.com/en/post/646397/ for some performance infos.

**Comment by DracoBlue** [comment]
I am collecting ideas at https://github.com/exozet/docker-php-fpm/wiki/Draft-for-new-Structure

**Comment by DracoBlue** [comment]
alpine version depends on https://github.com/docker-library/php/pull/1355

**Comment by DracoBlue** [comment]
A nginx unit version is available in the successor of this project at https://github.com/Endava/docker-php
