### ISSUE TITLE
How we handle php versions

### ISSUE THREAD

**Issue by DracoBlue** [exozet/docker-php-fpm#77]
Like discussed with @OskarStark, I would like to refactor the repository like this:

- master contains README.md with feature overview and hint on what the branches mean
- release/7.3, release/5.4 and so on
  - contains only the relevant stuff for this php version
  - travis pull requests build only this version range

Advantages:

- builds for PRs are faster
- travis doesn’t need to build old php versions if nothing changes

Disadvantage:

- ensuring a new extension is added to all versions is a matter of multiple pull requests

**Comment by OskarStark** [comment]
I am working on it...

Fixes #80
Fixes #82

**Branches:**
https://github.com/exozet/docker-php-fpm/tree/release/5.4
https://github.com/exozet/docker-php-fpm/tree/release/5.5
https://github.com/exozet/docker-php-fpm/tree/release/5.6
https://github.com/exozet/docker-php-fpm/tree/release/7.0
https://github.com/exozet/docker-php-fpm/tree/release/7.1
https://github.com/exozet/docker-php-fpm/tree/release/7.2
https://github.com/exozet/docker-php-fpm/tree/release/7.3

**I also updated the README files in the dedicated branches to reflect the correct used versions of the extensions.**

Please merge https://github.com/exozet/docker-php-fpm/pull/83

**Comment by OskarStark** [comment]
Closed by #83
