### ISSUE TITLE
config option --read-envelope-from might be needed for mailing

### ISSUE THREAD

**Issue by dennisexozet** [exozet/docker-php-fpm#81]
Hi,

we faced the problem that sending the mail died silently until we added the ```--read-envelope-from``` option to the ```PHP_SENDMAIL_PATH``` resulting in the config

```
PHP_SENDMAIL_PATH=/usr/bin/msmtp -t --host=mailhog --port=1025 --read-envelope-from
```

Maybe you should mention this in the docs.

We're using the image ```exozet/php-fpm:7.2.9-sudo```.

Greetz,
Dennis

**Comment by OskarStark** [comment]
Is this still relevant, and would you provide a PR?

**Comment by niepi** [comment]
@dennisexozet can we close this?
