### ISSUE TITLE
alpine images to fix unrelated CVEs

### ISSUE THREAD

**Issue by DracoBlue** [exozet/docker-php-fpm#92]
Currently our images are build from php-fpm without any tags or suffixes. Thus it is a debian with lots of packages and some php unrelated CVEs, which are not fixed.

Thus we should convert to alpine or at least deliver alpine and debian versions of the images (if possible).

Initial Idea:

1. new repository https://github.com/exozet/docker-php
2. new docker image: exozet/php
3. suffixes with sudo, root or and xdebug if necessary (`php:VERSION-fpm-xdebug-sudo/-root`)

    php:7.4.0
    php:7.4.0-sudo
    php:7.4.0-fpm-sudo
    php:7.4.0-fpm-xdebug-sudo

4. VERSION can be 7.4.0, 7.4 or 7
5. fpm suffix has fpm as entry point
6. sudo has sudo installed and www-data is allowed to sudo
7. root sets the images user to root
8. default user is www-data
9. xdebug suffix installs xdebug extension
10. images are based on official php alpine images (or we build them entirely from scratch - NO ... https://hub.docker.com/_/php/ does so many things!)

Final result:

1. same repository https://github.com/exozet/docker-php-fpm
2. alpine image have suffix -alpine
3. suffixes with sudo or and xdebug if necessary (`php:VERSION-xdebug`)

    php:7.4.0
    php:7.4.0-sudo
    php:7.4.0-xdebug

4. VERSION can be 7.4.0, 7.4 or 7
5. the images have fpm as entry point
6. sudo has sudo installed and www-data is allowed to sudo
7. default user is root
8. xdebug suffix installs xdebug extension
9. images are based on official php alpine images (or we build them entirely from scratch - NO ... https://hub.docker.com/_/php/ does so many things!)
[7.4.0-xdebug-alpine.i-report.txt](https://github.com/exozet/docker-php-fpm/files/3964715/7.4.0-xdebug-alpine.i-report.txt)
[7.4.0.i-report.txt](https://github.com/exozet/docker-php-fpm/files/3964716/7.4.0.i-report.txt)

**Comment by DracoBlue** [comment]
@niepi / @mbehrsing / @OskarStark / @Christian-Krupa / @hoffigk what do you think?

**Comment by DracoBlue** [comment]
We could also go for a fully environment variables driven approach and enable/disable extensions in docker-entrypoint.sh depending on the set environment variables.

**Comment by OskarStark** [comment]
Well alpine 👍🏻 why not, the other stuff seems quite complicated and should only be done if it’s worth and needed. For me the current state is enough and I don’t want to move into more and more dev ops direction again. Maybe there is something out there which fits all the requirements.
I am happy to support the decision and still keep an eye on this repo + maintenance, but you guys should decide, as you are using it in your daily business currently.

Cheers 🙂

**Comment by rmetzler** [comment]
One thing that has tripped me up is that xdebug is enabled per default in the current Exozet PHP images and you need to do something to disable it. I think it would be better (e.g. improve performance, keep build times down) if we would need to enable xdebug explicitly when needed.

For production ready containers I also think it would be nice to have very slim Docker containers with only the needed modules instead of everything. But I understand that it's often easier and faster to have a fat image for development. So this is probably a tradeoff.

**Comment by Christian-Krupa** [comment]
thumbs up for "images are based on official php alpine images"

**Comment by DracoBlue** [comment]
If we use PHP_INI_SCAN_DIR - we can maybe put a every expensive extension in a directory (eg xdebug) and load this only, if the environment variable is set to 1

**Comment by rmetzler** [comment]
I also need logging to STDOUT. Having short living cronjob containers logging into files in kubernetes doesn't work.

**Comment by niepi** [comment]
The CVEs I see as the biggest problem with the current image.

The size is not a real problem for me. I like that the current image has all the extension and tools it has, since this makes this useful to a lot of people and use cases. Providing multiple images with different features would make it more complicated to choose which image to use for not so experienced users.

I would suggest to create alpine images in the same repository in different branches/tags, with the same functionalities as the ubuntu images.

**Comment by DracoBlue** [comment]
> If we use PHP_INI_SCAN_DIR - we can maybe put a every expensive extension in a directory (eg xdebug) and load this only, if the environment variable is set to 1

does not work the way I wanted :(

**Comment by OskarStark** [comment]
> I would suggest to create alpine images in the same repository in different branches/tags, with the same functionalities as the ubuntu images.

Not sure the maintenance overhead is worth to maintain alpine and full distro images

**Comment by DracoBlue** [comment]
short clair scan on php 7.4.0 image:

```
[WARN] ▶ Image [exozet/php-fpm:7.4.0] contains 387 total vulnerabilities
[ERRO] ▶ Image [exozet/php-fpm:7.4.0] contains 387 unapproved vulnerabilities
```
[report.txt](https://github.com/exozet/docker-php-fpm/files/3944029/report.txt)

**Comment by rmetzler** [comment]
> I also need logging to STDOUT. Having short living cronjob containers logging into files in kubernetes doesn't work.

Max said this already works with Monolog and PHP 7.3 without the need for any sidecar container in Kubernetes. If that's the case, I would need documentation there.

Also something I needed to do for the `RedisSessionHandler` to not use the very short defaults for sessions:

```
RUN echo "session.cookie_lifetime=\${PHP_SESSION_COOKIE_LIFETIME};" >> /usr/local/etc/php/php.ini
RUN echo "session.gc_maxlifetime=\${PHP_SESSION_GC_MAXLIFETIME};" >> /usr/local/etc/php/php.ini
```

**Comment by DracoBlue** [comment]
I created an quay.io account and build for alpine+non-alpine images an upload.

at https://quay.io/repository/exozet/php-fpm?tab=tags we will see now the report of CVEs

<img width="1289" alt="Bildschirmfoto 2019-12-15 um 08 53 27" src="https://user-images.githubusercontent.com/35926/70859888-85a4c400-1f1a-11ea-9470-20dd984ece65.png">

**Comment by DracoBlue** [comment]
In https://github.com/exozet/docker-php-fpm/pull/119#issue-351961394 you can now see the differences in php.ini output of the alpine and the non-alpine version!

**Comment by DracoBlue** [comment]
Hello.

At https://github.com/exozet/docker-php-fpm/pull/119#issue-351961394 you can now see my progress to get a alpine version of our docker image. It also has a detailed list of the differences between those two images in terms of the php.ini output (seems like some non-obvious imagemagick formats and some config for curl are disabled on alpine -> please check!!).

0. use -alpine suffix on any 7.4.x image
1. xdebug is not enabled by default anymore. use -xdebug-alpine suffix to enable
2. php log to stdout for errors is enabled by default
3. it's based on alpine and not debian anymore
4. it has 0 known CVEs instead of our debian based one (420 CVEs) -> see the reports here https://quay.io/repository/exozet/php-fpm?tab=tags (they are autogenerated on each build)
5. the alpine image is just 105mb instead of currently 263mb for the old image
6. the cron logic runs crond now directly without upstart -> I tested, but it might behave different. be aware!

See it as a beta. Hopefully it works well, then I will try to provide 7.3.x and so on alpine images, too.
